apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: apis
  description: A collection of all apis
spec:
  targets:
    - ./apis/petstore.yaml
    - ./apis/nexus-repo-manager-3.yaml
    - ./apis/hello-world-api.yaml
    - ./apis/hello-world-trpc-api.yaml
    - ./apis/petstore-api.yaml
    - ./apis/petstore-webhook-api.yaml
    - ./apis/spotify-api.yaml
    - ./apis/streetlights-api.yaml
    - ./apis/swapi-graphql.yaml
    - ./apis/wayback-archive-api.yaml
    - ./apis/wayback-search-api.yaml    
